prefix p: <upload-base/predicate/>
prefix foaf: <http://xmlns.com/foaf/0.1/>

select (?y as ?Year) (?f as ?Field) (count(?p) as ?Primes)
where {
?p p:year ?y.
?p p:field ?fi.
?fi foaf:name ?f.
}
group by ?y ?f
order by ?y ?f
