prefix p: <upload-base/predicate/>
prefix foaf: <http://xmlns.com/foaf/0.1/>

SELECT (?y as ?Annee) (?g as ?Gender) (count(?nb) as ?Beneficiaires)
WHERE {
?p p:year ?y.
?p p:beneficiaires ?nb.
?p foaf:gender ?g
}
group by ?y ?g
order by ?y ?g
