PREFIX frapo: <http://purl.org/cerif/frapo/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT (STR(?y) as ?Annee) (?g as ?Gender) (STR(count(?nb)) as ?Beneficiaires)
WHERE {
  ?prime frapo:hasAwardDate ?y.
  ?prime frapo:funds ?group.
  ?group foaf:gender ?g.
  ?group frapo:hasHeadcount ?nb.
}
group by ?y ?g
order by ?y ?g
