PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbp: <http://dbpedia.org/property/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX georss: <http://www.georss.org/georss>

CONSTRUCT {
		_:primes ?pInstitution ?URI_Inst;
    	dbp:year ?an;
      foaf:gender ?sexe;
      ?pBeneficiaires ?benef;
      ?pField ?URI_Field;
      ?pProfGroup ?URI_ProfGroup;
      ?pIDEX ?URI_IDEX.

    ?URI_Inst a dbo:EducationalInstitution;
	   foaf:name ?etablissement;
     ?pInstCode ?code_uai;
     ?pAcademy ?URI_Academy;
     ?pPRES ?URI_PRES;
     ?pRegion ?URI_Region;
     georss:point ?geolocalisation.

    ?URI_Field a skos:Concept;
      foaf:name ?secteur_disciplinaire;
      ?pFieldCode ?cnu.

    ?URI_ProfGroup a ?tProfessionGroup;
      foaf:name ?groupe_de_corps;
      ?pProfGroupCode ?cgc.

    ?URI_IDEX a ?tIDEX;
      foaf:name ?IDEX;
      ?pIdexCode ?codeIDEX.

    ?URIAcademy a ?tAcademy;
      foaf:name ?academie;
      ?pAcademyCode ?codeAca.

    ?URI_PRES a ?tPRES;
      foaf:name ?PRES;
      ?pPresCode ?codePRES.

    ?URI_Region a dbo:Region;
      foaf:name ?region;
      ?pRegionCode ?codeReg.

}
FROM <file>
WHERE {

	BIND (URI(CONCAT('institution/', ?code_uai)) AS ?URI_Inst)
  BIND (URI(CONCAT('field/', ?code_secteur_cnu)) AS ?URI_Field)
  BIND (URI(CONCAT('profGroup/', ?code_groupe_corps)) AS ?URI_ProfGroup)
  BIND (URI(CONCAT('idex/', ?code_idex)) AS ?URI_IDEX)
  BIND (URI(CONCAT('academy/', ?code_academie)) AS ?URI_Academy)
  BIND (URI(CONCAT('pres/', ?code_pres)) AS ?URI_PRES)
  BIND (URI(CONCAT('region/', ?code_region)) AS ?URI_Region)

  BIND (URI('type/ProfessionGroup') AS ?tProfessionGroup)
  BIND (URI('type/IDEX') AS ?tIDEX)
  BIND (URI('type/Academy') AS ?tAcademy)
  BIND (URI('type/PRES') AS ?tPRES)

  BIND (URI('predicate/institution') AS ?pInstitution)
  BIND (URI('predicate/field') AS ?pField)
  BIND (URI('predicate/professionGroup') AS ?pProfGroup)
  BIND (URI('predicate/IDEX') AS ?pIDEX)
  BIND (URI('predicate/academy') AS ?pAcademy)
  BIND (URI('predicate/PRES') AS ?pPRES)
  BIND (URI('predicate/region') AS ?pRegion)
  BIND (URI('predicate/beneficiaires') AS ?pBeneficiaires)
  BIND (URI('predicate/instCode') AS ?pInstCode)
  BIND (URI('predicate/fieldCode') AS ?pFieldCode)
  BIND (URI('predicate/profGroupCode') AS ?pProfGroupCode)
  BIND (URI('predicate/idexCode') AS ?pIdexCode)
  BIND (URI('predicate/academyCode') AS ?pAcademyCode)
  BIND (URI('predicate/presCode') AS ?pPresCode)
  BIND (URI('predicate/regionCode') AS ?pRegionCode)

  BIND (xsd:integer(?beneficiaires) AS ?benef)
  BIND (xsd:integer(?annee) AS ?an)
  BIND (xsd:integer(?code_secteur_cnu) AS ?cnu)
  BIND (xsd:integer(?code_groupe_corps) AS ?cgc)
  BIND (xsd:integer(?code_idex) AS ?codeIDEX)
  BIND (xsd:integer(?code_academie) AS ?codeAca)
  BIND (xsd:integer(?code_pres) AS ?codePRES)
  BIND (xsd:integer(?code_region) AS ?codeReg)
}
